#!/bin/sh
hook_file=`pwd`/.git/hooks/prepare-commit-msg

cat > $hook_file <<- EOM
#!/bin/sh

NAME=\$(git config user.name)
EMAIL=\$(git config user.email)

if [ -z "\$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "\$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: \$NAME <\$EMAIL>" \
    --in-place "\$1"	
EOM


chmod +x $hook_file
echo "If no errors were printed, commits will now be automatically signed off"
